=== callidaria/pen-testing/data/xml/inventoryEntries.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="entries">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entry">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="count" type="xs:integer"/>
                            <xs:element name="weight" type="xs:integer"/>
							<xs:element name="prize" type="xs:integer"/>
							<xs:element name="category_id" type="xs:integer"/>
                        </xs:sequence>
						<xs:attribute name="section" type="xs:integer" />
						<xs:attribute name="place" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="nameMustBeUnique">
			<xs:selector xpath="entry/name"/>
            <xs:field xpath="." />
		</xs:unique>
        <xs:unique name="sectionPlaceMustBeUnique">
			<xs:selector xpath="entry" />
			<xs:field xpath="@section" />
            <xs:field xpath="@place" />
        </xs:unique>
        
    </xs:element>

    <xs:simpleType name="shelfType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="999"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== callidaria/pen-testing/data/xml/inventoryEntries.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
a position has 75-80 bytes
-->
<entries xsi:noNamespaceSchemaLocation="inventoryEntries.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entry id="0" section="100" place="100">
    <name>Simple Pen</name>
    <count>100000</count>
    <weight>12</weight>
    <prize>99</prize>
    <category_id>1</category_id>
  </entry>
  <entry id="1" section="100" place="200">
    <name>Big Pen</name>
    <count>400</count>
    <weight>20</weight>
    <prize>199</prize>
    <category_id>1</category_id>
  </entry>
  <entry id="2" section="100" place="300">
    <name>XL Pen</name>
    <count>400</count>
    <weight>20</weight>
    <prize>199</prize>
    <category_id>1</category_id>
  </entry>
</entries>

=== callidaria/pen-testing/data/inventoryEntries.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><entries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="inventoryEntries.xsd"><entry area="0" place="1"><name>Blauer Stift</name><count>100</count><weight>1000</weight><prize>100</prize><category_id>0</category_id></entry><entry area="0" place="2"><name>Kategorienverwaltung im Men√º</name><count>1</count><weight>1</weight><prize>1</prize><category_id>0</category_id></entry></entries>
