=== callidaria/pen-testing/data/xml/products.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="product">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="count" type="xs:integer"/>
                            <xs:element name="weight" type="xs:integer"/>
							<xs:element name="prize" type="xs:integer"/>
							<xs:element name="category_id" type="xs:integer"/>
                        </xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueUID">
			<xs:selector xpath="product" /> 
			<xs:field xpath="@id" /> 
		</xs:unique>
    </xs:element>    
</xs:schema>

=== callidaria/pen-testing/xml/products.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
a product has ~ 140 bytes
-->
<products xsi:noNamespaceSchemaLocation="products.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <product id="1">
    <name>Simple Pen</name>
    <count>100000</count>
    <weight>12</weight>
    <prize>99</prize>
    <category_id>1</category_id>
  </product>
  <product id="2">
    <name>Big Pen</name>
    <count>400</count>
    <weight>20</weight>
    <prize>199</prize>
    <category_id>1</category_id>
  </product>
  <product id="3">
    <name>Big Pen</name>
    <count>400</count>
    <weight>20</weight>
    <prize>199</prize>
    <category_id>1</category_id>
  </product>
</products>
